(in-package :cl-user)
(push :travis *features*)
(ql:quickload "py4cl2/tests")
(print (py4cl2:config-var 'py4cl2:pycmd))
(let ((report (py4cl2/tests:run)))
  (princ report)
  (when (or (plusp (slot-value report 'clunit::failed))
            (plusp (slot-value report 'clunit::errors)))
    (uiop:quit 1)))
(format t "!!ALL TESTS RAN SUCCESSFULLY!!")
(uiop:quit 0)
